version: '3.8'

services:
  postcard-processor:
    build: .
    volumes:
      - ./app:/app/app
      - ./data:/app/data
    environment:
      - OCR_ENGINE=tessaract
      - ENHANCE_IMAGE=true
      - AUTO_DESKEW=true
      - TRY_ROTATIONS=false
      - MIN_CONFIDENCE=0.2
      - TROCR_MODEL=${TROCR_MODEL:-microsoft/trocr-base-handwritten}
      - INPUT_DIR=/app/data/input
      - OUTPUT_DIR=/app/data/output
      - PROCESSED_DIR=/app/data/processed
      - PYTHONUNBUFFERED=1
      - MIN_CONFIDENCE=0.1
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]